title: The first learning path
description: The first learning path
steps:
  - title: Start walking
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    course: The first course
    description: 'Rock and roll '
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
